import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync,statSync} from 'node:fs';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import postcss from 'postcss';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),source=f=>readFileSync(path.join(root,f),'utf8'),req=createRequire(path.join(root,'package.json'));
function canonical(n){if(ts.isAsExpression(n)||ts.isNonNullExpression(n))return canonical(n.expression);if(ts.isStringLiteral(n)||ts.isNoSubstitutionTemplateLiteral(n))return ['text',n.text];if(ts.isIdentifier(n))return ['name',n.text];const c=[];ts.forEachChild(n,x=>{if(!ts.isTypeNode(x))c.push(canonical(x));});return [ts.SyntaxKind[n.kind],c];}
for(const [route,expected] of Object.entries(JSON.parse(source('tests/auth/fixtures/retirement-controller-contracts.json'))))test(`${route}: full original validation, requests, sequencing, feedback and redirect handlers`,()=>{
 const text=source(`app/${route}/page.tsx`).replaceAll('catch (caught: unknown) {\n      const err = caught as { message: string }','catch (err) {');
 const ast=ts.createSourceFile(route,text,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),actual={};function visit(n){if(ts.isVariableDeclaration(n)&&ts.isIdentifier(n.name)&&n.name.text.startsWith('handle')&&n.initializer)actual[n.name.text]=canonical(n.initializer);ts.forEachChild(n,visit);}visit(ast);assert.deepEqual(actual,expected);
});
const cache=new Map();function load(file){
 const filename=path.resolve(root,file);if(cache.has(filename))return cache.get(filename).exports;const loaded={exports:{}};cache.set(filename,loaded);
 const code=ts.transpileModule(source(file),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;
 const local=name=>{if(name.endsWith('.css'))return {};if(!name.startsWith('@/')&&!name.startsWith('.'))return req(name);const target=name.startsWith('@/')?path.join(root,name.slice(2)):path.resolve(path.dirname(filename),name);const resolved=[target,target+'.ts',target+'.tsx'].find(f=>existsSync(f)&&statSync(f).isFile());assert.ok(resolved,name);return load(path.relative(root,resolved));};new Function('require','module','exports',code)(local,loaded,loaded.exports);return loaded.exports;
}
const {AuthView}=load('components/auth/auth-view.tsx');
const defaults={mode:'signin',email:'',setEmail:()=>{},password:'',setPassword:()=>{},fullName:'',setFullName:()=>{},loading:false,error:'',onAction:()=>{},onGoogle:()=>{}};
const html=props=>renderToStaticMarkup(React.createElement(AuthView,{...defaults,...props}));
function nodes(node,result=[]){if(!React.isValidElement(node))return result;result.push(node);React.Children.forEach(node.props.children,x=>nodes(x,result));return result;}
test('sign-in labels, autocomplete, Google and navigation use real shared presentation',()=>{const markup=html({});for(const s of ['for="auth-email"','for="auth-password"','autoComplete="email"','autoComplete="current-password"','href="/forgot-password"','href="/sign-up"','Continue with Google'])assert.ok(markup.includes(s),s);assert.doesNotMatch(markup,/Sign in with X|Keep me logged in/);});
test('signup retains existing fields without new identity or agreement controls',()=>{const markup=html({mode:'signup'});assert.match(markup,/autoComplete="name"/);assert.match(markup,/autoComplete="new-password"/);assert.match(markup,/href="\/sign-in"/);assert.doesNotMatch(markup,/type="checkbox"|Seller|Student|Creator/);});
test('forgot password exposes existing email action only',()=>{const markup=html({mode:'forgot',onGoogle:undefined});assert.match(markup,/Email address/);assert.doesNotMatch(markup,/type="password"|Continue with Google/);assert.match(markup,/Send reset link/);});
test('provider error is escaped, announced and associated with fields',()=>{const markup=html({error:'Provider <message> & details'});assert.match(markup,/role="alert" id="auth-error"/);assert.match(markup,/aria-invalid="true" aria-describedby="auth-error"/);assert.match(markup,/Provider &lt;message&gt; &amp; details/);});
test('loading disables both auth buttons and exposes status',()=>{const markup=html({email:'fixture@example.invalid',password:'fixture',loading:true});assert.match(markup,/Signing in\.\.\./);assert.match(markup,/aria-busy="true"/);assert.equal((markup.match(/disabled=""/g)||[]).length,2);assert.match(markup,/role="status"/);});
test('success renders long email and canonical return without credential controls',()=>{const markup=html({mode:'signup',success:true,email:'a'.repeat(180)+'@example.invalid'});assert.match(markup,/Check your email/);assert.match(markup,/href="\/sign-in"/);assert.doesNotMatch(markup,/<input/);});
test('controlled callbacks and original Enter submission positions remain',()=>{let action=0,email='';const tree=nodes(AuthView({...defaults,email:'fixture@example.invalid',onAction:()=>action++,setEmail:value=>{email=value;}}));const input=tree.find(x=>x.type==='input'&&x.props.id==='auth-email');input.props.onChange({target:{value:'long@example.invalid'}});assert.equal(email,'long@example.invalid');input.props.onKeyDown({key:'Enter'});assert.equal(action,0);tree.find(x=>x.type==='input'&&x.props.id==='auth-password').props.onKeyDown({key:'Enter'});assert.equal(action,1);nodes(AuthView({...defaults,mode:'forgot',onAction:()=>action++})).find(x=>x.type==='input').props.onKeyDown({key:'Enter'});assert.equal(action,2);});
test('legacy URLs share canonical controllers without old layouts',()=>{for(const [old,current] of [['signin','sign-in'],['signup','sign-up']])assert.ok(source(`app/full-width-pages/(auth)/${old}/page.tsx`).includes(`@/app/${current}/page`));assert.doesNotMatch(source('app/full-width-pages/(auth)/layout.tsx'),/GridShape|ThemeTogglerTwo/);});
test('canonical Admin route is retained without duplicate overview',()=>{assert.ok(existsSync(path.join(root,'app/admin/page.tsx')));assert.equal(existsSync(path.join(root,'app/admin/dashboard/page.tsx')),false);assert.doesNotMatch(source('components/admin/AdminSidebar.tsx'),/\/admin\/dashboard/);});
test('original legacy primitives and eleven template packages are absent',()=>{const pkg=JSON.parse(source('package.json'));for(const p of ['flatpickr','@fullcalendar/core','@fullcalendar/daygrid','@fullcalendar/interaction','@fullcalendar/list','@fullcalendar/react','@fullcalendar/timegrid','@react-jvectormap/core','@react-jvectormap/world','jsvectormap','react-dropzone'])assert.equal(pkg.dependencies[p],undefined);for(const f of ['components/auth/SignInForm.tsx','components/auth/SignUpForm.tsx','components/form/input/Checkbox.tsx','layout/AppSidebar.tsx'])assert.equal(existsSync(path.join(root,f)),false);});
test('auth uses existing scoped tokens and shared dark variant survives cleanup',()=>{const css=source('app/styles/auth.css'),tokens=source('app/styles/workspace-tokens.css');postcss.parse(css);for(const name of css.match(/--cc-[\w-]+/g)||[])assert.ok(tokens.includes(name+':'),name);assert.match(css,/:focus-visible/);assert.match(css,/prefers-reduced-motion/);assert.match(source('app/globals.css'),/@custom-variant dark/);assert.doesNotMatch(source('app/globals.css'),/flatpickr|--color-boxdark|@utility menu-item/);});
test('fixture cannot authenticate and retains the guarded noindex parent',()=>{assert.doesNotMatch(source('app/design/command-center/auth/page.tsx'),/createClient|fetch\(|supabase/);const layout=source('app/design/command-center/layout.tsx');assert.match(layout,/DESIGN_PREVIEW_ENABLED/);assert.match(layout,/notFound\(\)/);assert.match(layout,/index: false/);});
