import type { PremiumResource } from "@/types/portfolio";

export const PREMIUM_RESOURCES: PremiumResource[] = [
  {
    id: "capability-statement",
    title: "PurpleSoftHub Capability Statement",
    slug: "capability-statement",
    description: "A concise overview of our services, process, selected work, and how we partner with growing African businesses.",
    category: "Capability Statement",
    version: "2026.1",
    tags: ["Agency", "Services", "Pitch"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-capability-statement.pdf",
    previewUrl: null,
    relatedServices: ["Website", "Brand Identity", "Marketing"],
    emailGate: true,
    downloadCount: 186,
    status: "published",
    createdAt: "2026-01-12T00:00:00Z",
    updatedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "company-profile",
    title: "Company Profile",
    slug: "company-profile",
    description: "Our full company profile — who we are, what we build, and the industries we serve.",
    category: "Company Profile",
    version: "2026.2",
    tags: ["Corporate", "About"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-company-profile.pdf",
    previewUrl: null,
    relatedServices: ["Website", "Brand Identity", "Printing"],
    emailGate: true,
    downloadCount: 242,
    status: "published",
    createdAt: "2026-02-04T00:00:00Z",
    updatedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "corporate-profile",
    title: "Corporate Profile",
    slug: "corporate-profile",
    description: "A board-ready corporate profile for partnerships, procurement, and institutional introductions.",
    category: "Corporate Profile",
    version: "2026.1",
    tags: ["Corporate", "Partnerships"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-corporate-profile.pdf",
    previewUrl: null,
    relatedServices: ["Website", "Printing", "Photography"],
    emailGate: true,
    downloadCount: 97,
    status: "published",
    createdAt: "2026-03-18T00:00:00Z",
    updatedAt: "2026-07-20T00:00:00Z",
  },
  {
    id: "sponsorship-deck",
    title: "Sponsorship Deck Template",
    slug: "sponsorship-deck",
    description: "A sample sponsorship deck showing how we structure value, packages, and visual storytelling for events and brands.",
    category: "Sponsorship Deck",
    version: "2025.4",
    tags: ["Events", "Sponsorship"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-sponsorship-deck.pdf",
    previewUrl: null,
    relatedServices: ["Brand Identity", "Social Media", "Printing"],
    emailGate: false,
    downloadCount: 64,
    status: "published",
    createdAt: "2025-11-02T00:00:00Z",
    updatedAt: "2026-04-11T00:00:00Z",
  },
  {
    id: "sponsorship-proposal",
    title: "Sponsorship Proposal Sample",
    slug: "sponsorship-proposal",
    description: "A narrative sponsorship proposal with offer structure, audience data, and activation ideas.",
    category: "Sponsorship Proposal",
    version: "2025.3",
    tags: ["Events", "Proposal"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-sponsorship-proposal.pdf",
    previewUrl: null,
    relatedServices: ["Brand Identity", "Marketing"],
    emailGate: true,
    downloadCount: 41,
    status: "published",
    createdAt: "2025-10-09T00:00:00Z",
    updatedAt: "2026-03-02T00:00:00Z",
  },
  {
    id: "brand-guidelines",
    title: "Brand Guidelines Sample",
    slug: "brand-guidelines",
    description: "A sample brand book covering logo use, colour, type, imagery, and application rules.",
    category: "Brand Guidelines",
    version: "2026.1",
    tags: ["Branding", "Identity"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-brand-guidelines.pdf",
    previewUrl: null,
    relatedServices: ["Brand Identity", "Printing", "Website"],
    emailGate: false,
    downloadCount: 118,
    status: "published",
    createdAt: "2026-01-28T00:00:00Z",
    updatedAt: "2026-06-14T00:00:00Z",
  },
  {
    id: "annual-report",
    title: "Annual Report Sample",
    slug: "annual-report",
    description: "Editorial layout sample for annual reports, impact reviews, and investor updates.",
    category: "Annual Report",
    version: "2025.1",
    tags: ["Editorial", "Print"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-annual-report.pdf",
    previewUrl: null,
    relatedServices: ["Printing", "Photography", "Brand Identity"],
    emailGate: true,
    downloadCount: 33,
    status: "published",
    createdAt: "2025-12-12T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "magazine",
    title: "Magazine Spread Sample",
    slug: "magazine",
    description: "Publication design sample with cover, contents, and feature spreads.",
    category: "Magazine",
    version: "2025.2",
    tags: ["Editorial", "Print"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-magazine.pdf",
    previewUrl: null,
    relatedServices: ["Printing", "Photography", "Brand Identity"],
    emailGate: false,
    downloadCount: 29,
    status: "published",
    createdAt: "2025-09-20T00:00:00Z",
    updatedAt: "2026-01-08T00:00:00Z",
  },
  {
    id: "product-catalogue",
    title: "Product Catalogue Sample",
    slug: "product-catalogue",
    description: "A product catalogue layout with grid systems, product cards, and specification pages.",
    category: "Product Catalogue",
    version: "2026.1",
    tags: ["Retail", "Print"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-product-catalogue.pdf",
    previewUrl: null,
    relatedServices: ["Printing", "Photography", "Website"],
    emailGate: true,
    downloadCount: 55,
    status: "published",
    createdAt: "2026-02-22T00:00:00Z",
    updatedAt: "2026-05-19T00:00:00Z",
  },
  {
    id: "marketing-brochure",
    title: "Marketing Brochure",
    slug: "marketing-brochure",
    description: "A compact brochure that introduces PurpleSoftHub services and proof points.",
    category: "Marketing Brochure",
    version: "2026.1",
    tags: ["Marketing", "Print"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-brochure.pdf",
    previewUrl: null,
    relatedServices: ["Marketing", "Printing", "Brand Identity"],
    emailGate: false,
    downloadCount: 77,
    status: "published",
    createdAt: "2026-03-03T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "training-manual",
    title: "Training Manual Sample",
    slug: "training-manual",
    description: "Structured training manual layout for academies, onboarding, and internal playbooks.",
    category: "Training Manual",
    version: "2025.1",
    tags: ["Education", "Editorial"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-training-manual.pdf",
    previewUrl: null,
    relatedServices: ["Website", "Brand Identity"],
    emailGate: true,
    downloadCount: 18,
    status: "published",
    createdAt: "2025-08-14T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "business-proposal",
    title: "Business Proposal Sample",
    slug: "business-proposal",
    description: "A proposal document showing scope, timeline, investment, and deliverable framing.",
    category: "Business Proposal",
    version: "2026.1",
    tags: ["Sales", "Proposal"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-business-proposal.pdf",
    previewUrl: null,
    relatedServices: ["Website", "Brand Identity", "Marketing"],
    emailGate: true,
    downloadCount: 52,
    status: "published",
    createdAt: "2026-04-07T00:00:00Z",
    updatedAt: "2026-07-09T00:00:00Z",
  },
  {
    id: "event-branding-kit",
    title: "Event Branding Kit",
    slug: "event-branding-kit",
    description: "A sample kit covering backdrops, badges, social frames, and stage graphics.",
    category: "Event Branding Kit",
    version: "2025.2",
    tags: ["Events", "Branding"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-event-kit.pdf",
    previewUrl: null,
    relatedServices: ["Brand Identity", "Social Media", "Photography"],
    emailGate: false,
    downloadCount: 44,
    status: "published",
    createdAt: "2025-07-30T00:00:00Z",
    updatedAt: "2026-02-18T00:00:00Z",
  },
  {
    id: "investment-pitch-deck",
    title: "Investment Pitch Deck",
    slug: "investment-pitch-deck",
    description: "A sample investor deck with narrative flow, traction slides, and visual discipline.",
    category: "Investment Pitch Deck",
    version: "2026.1",
    tags: ["Startup", "Pitch"],
    coverImage: null,
    pdfUrl: "/downloads/purplesofthub-pitch-deck.pdf",
    previewUrl: null,
    relatedServices: ["Brand Identity", "Website", "Marketing"],
    emailGate: true,
    downloadCount: 71,
    status: "published",
    createdAt: "2026-05-11T00:00:00Z",
    updatedAt: "2026-07-28T00:00:00Z",
  },
];

export const RESOURCE_CATEGORIES = Array.from(new Set(PREMIUM_RESOURCES.map((item) => item.category)));
