export type BillingType = 'one-time' | 'monthly' | 'yearly' | 'custom'

export type ServiceCategory =
  | 'development'
  | 'marketing'
  | 'design'
  | 'music'
  | 'support'
  | 'content'

export interface ServicePlan {
  id: string
  name: string
  priceNGN: number
  priceUSD: number
  billingType: BillingType
  delivery: string
  description: string
  features: string[]
  highlighted?: boolean
  isCustom?: boolean
  badge?: string
}

export interface Service {
  id: string
  slug: string
  name: string
  tagline: string
  description: string
  category: ServiceCategory
  icon: string
  startingPriceNGN: number
  startingPriceUSD: number
  billingType: BillingType
  payOnline: boolean
  plans: ServicePlan[]
}

export const SERVICES: Service[] = [
  // â”€â”€ WEB DEVELOPMENT â”€â”€
  {
    id: 'web-development',
    slug: 'web-development',
    name: 'Web Development',
    tagline: 'Professional websites that convert visitors into clients',
    description: 'We build fast, modern, and conversion-optimized websites for businesses, startups, and creators across Africa and worldwide. From simple landing pages to complex SaaS platforms.',
    category: 'development',
    icon: '🌐',
    startingPriceNGN: 450000,
    startingPriceUSD: 300,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'web-starter',
        name: 'Starter',
        priceNGN: 450000,
        priceUSD: 300,
        billingType: 'one-time',
        delivery: '2 weeks',
        description: 'Perfect for small businesses and personal brands',
        features: [
          '1â€“3 pages',
          'Mobile responsive design',
          'Contact form',
          'Basic SEO setup',
          'WhatsApp chat button',
          '1 month free support',
        ],
      },
      {
        id: 'web-essential',
        name: 'Essential',
        priceNGN: 750000,
        priceUSD: 500,
        billingType: 'one-time',
        delivery: '3 weeks',
        description: 'Ideal for growing businesses needing more pages',
        features: [
          'Up to 5 pages',
          'Mobile responsive design',
          'Contact form + Newsletter',
          'On-page SEO',
          'Google Analytics setup',
          'Social media integration',
          '2 months free support',
        ],
      },
      {
        id: 'web-professional',
        name: 'Professional',
        priceNGN: 975000,
        priceUSD: 650,
        billingType: 'one-time',
        delivery: '4 weeks',
        description: 'For established businesses wanting premium quality',
        features: [
          'Up to 8 pages',
          'Premium UI/UX design',
          'Contact form + Newsletter',
          'Blog/CMS setup',
          'Full SEO optimization',
          'Speed optimization',
          'Payment integration',
          '2 months free support',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'web-advanced',
        name: 'Advanced',
        priceNGN: 1200000,
        priceUSD: 800,
        billingType: 'one-time',
        delivery: '5 weeks',
        description: 'For businesses needing advanced features',
        features: [
          'Up to 12 pages',
          'Custom animations',
          'E-commerce ready',
          'Member/login area',
          'Advanced SEO',
          'Email marketing setup',
          'API integrations',
          '3 months free support',
        ],
      },
      {
        id: 'web-premium',
        name: 'Premium',
        priceNGN: 1800000,
        priceUSD: 1200,
        billingType: 'one-time',
        delivery: '6 weeks',
        description: 'Full-featured website with client portal',
        features: [
          'Unlimited pages',
          'Client dashboard/portal',
          'Full e-commerce',
          'Payment processing',
          'Custom admin panel',
          'Advanced animations',
          'Multi-language support',
          '4 months free support',
        ],
      },
      {
        id: 'web-elite',
        name: 'Elite',
        priceNGN: 2550000,
        priceUSD: 1700,
        billingType: 'one-time',
        delivery: '8 weeks',
        description: 'Enterprise-grade website with SaaS features',
        features: [
          'Everything in Premium',
          'SaaS functionality',
          'Subscription billing',
          'User management system',
          'Advanced analytics',
          'Third-party API integrations',
          '6 months free support',
        ],
      },
      {
        id: 'web-executive',
        name: 'Executive',
        priceNGN: 3270000,
        priceUSD: 2180,
        billingType: 'one-time',
        delivery: '10 weeks',
        description: 'Complete digital platform with mobile app',
        features: [
          'Everything in Elite',
          'Mobile app (iOS + Android)',
          'Custom CRM features',
          'Workflow automation',
          'White-label ready',
          'Dedicated project manager',
          '6 months free support',
        ],
      },
      {
        id: 'web-platinum',
        name: 'Platinum',
        priceNGN: 4845000,
        priceUSD: 2850,
        billingType: 'one-time',
        delivery: '12 weeks',
        description: 'Full digital ecosystem for large businesses',
        features: [
          'Everything in Executive',
          'Full SaaS platform',
          'AI feature integration',
          'Multi-tenant architecture',
          'Advanced security',
          'Performance SLA',
          '12 months free support',
        ],
      },
      {
        id: 'web-diamond',
        name: 'Diamond',
        priceNGN: 8500000,
        priceUSD: 5000,
        billingType: 'one-time',
        delivery: '16+ weeks',
        description: 'Enterprise digital transformation project',
        features: [
          'Everything in Platinum',
          'Dedicated development team',
          'Custom AI/ML features',
          'Enterprise integrations',
          'Staff training',
          'Ongoing development retainer',
          '24 months free support',
        ],
        badge: 'Best Value',
      },
    ],
  },

  // â”€â”€ FACEBOOK/INSTAGRAM ADS â”€â”€
  {
    id: 'facebook-ads',
    slug: 'facebook-and-instagram-ads',
    name: 'Facebook & Instagram Ads',
    tagline: 'Meta advertising that drives real results for your business',
    description: 'Professional Facebook and Instagram ad management. We build, test, and scale campaigns that consistently deliver results. Ad spend is paid directly to Meta.',
    category: 'marketing',
    icon: '📘',
    startingPriceNGN: 42000,
    startingPriceUSD: 30,
    billingType: 'monthly',
    payOnline: true,
    plans: [
      {
        id: 'ads-flex',
        name: 'Flex Weekly',
        priceNGN: 42000,
        priceUSD: 30,
        billingType: 'monthly',
        delivery: 'Weekly',
        description: 'Test campaigns with flexible weekly commitment',
        features: [
          '1 active campaign',
          '2-3 ad creatives/week',
          'Facebook OR Instagram',
          'Basic audience targeting',
          'Weekly performance report',
          'WhatsApp support',
        ],
        badge: 'Best for Testing',
      },
      {
        id: 'ads-starter',
        name: 'Starter',
        priceNGN: 150000,
        priceUSD: 107,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Perfect for businesses starting with paid ads',
        features: [
          '1 active campaign',
          '3-5 ad creatives/month',
          'Facebook OR Instagram',
          'Basic audience targeting',
          'Weekly optimization',
          'Monthly performance report',
          'Recommended ad spend: â‚¦150K-â‚¦300K',
        ],
      },
      {
        id: 'ads-growth',
        name: 'Growth',
        priceNGN: 250000,
        priceUSD: 178,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Scale your reach with Facebook AND Instagram',
        features: [
          '3 active campaigns',
          '8-10 ad creatives/month',
          'Facebook AND Instagram',
          'Advanced targeting + lookalikes',
          'Retargeting campaigns',
          'A/B testing',
          'Bi-weekly strategy calls',
          'Bi-weekly performance report',
          'Recommended ad spend: â‚¦300K-â‚¦750K',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'ads-scale',
        name: 'Scale',
        priceNGN: 400000,
        priceUSD: 285,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'For businesses ready to dominate their market',
        features: [
          'Unlimited campaigns',
          'Unlimited ad creatives',
          'Full-funnel strategy',
          'Advanced pixel setup',
          'Custom audiences',
          'Competitor analysis',
          'Weekly strategy calls',
          'Weekly detailed report',
          'Recommended ad spend: â‚¦750K+',
        ],
      },
      {
        id: 'ads-enterprise',
        name: 'Enterprise',
        priceNGN: 600000,
        priceUSD: 428,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Full-service Meta advertising with dedicated team',
        features: [
          'Everything in Scale',
          'Dedicated account manager',
          'Custom automation & funnels',
          'Creative production support',
          'Multi-account management',
          'Monthly in-depth audit',
          'Priority support 7 days/week',
          'Recommended ad spend: â‚¦1.5M+',
        ],
      },
    ],
  },

  // â”€â”€ MOBILE APP DEVELOPMENT â”€â”€
  {
    id: 'mobile-app-development',
    slug: 'mobile-app-development',
    name: 'Mobile App Development',
    tagline: 'Cross-platform mobile apps users love on iOS and Android',
    description: 'We build beautiful, high-performance mobile apps using React Native and Flutter. From simple utility apps to complex marketplace platforms â€” delivered on time.',
    category: 'development',
    icon: '📱',
    startingPriceNGN: 750000,
    startingPriceUSD: 500,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'app-starter',
        name: 'Starter',
        priceNGN: 750000,
        priceUSD: 500,
        billingType: 'one-time',
        delivery: '4-6 weeks',
        description: 'Simple app for one platform â€” iOS or Android',
        features: [
          'iOS OR Android',
          'Up to 5 screens',
          'User authentication',
          'Basic database integration',
          'React Native/Flutter',
          'App Store submission',
          '1 month free support',
        ],
      },
      {
        id: 'app-growth',
        name: 'Growth',
        priceNGN: 1500000,
        priceUSD: 1071,
        billingType: 'one-time',
        delivery: '6-10 weeks',
        description: 'Cross-platform app for iOS and Android',
        features: [
          'iOS AND Android',
          'Up to 15 screens',
          'User auth + profiles',
          'Database + backend',
          'Push notifications',
          'In-app payments',
          'Admin dashboard',
          'App Store + Play Store submission',
          '2 months free support',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'app-pro',
        name: 'Pro',
        priceNGN: 2500000,
        priceUSD: 1785,
        billingType: 'one-time',
        delivery: '10-16 weeks',
        description: 'Complex app with advanced features and backend',
        features: [
          'iOS AND Android',
          'Unlimited screens',
          'Custom backend/API',
          'Payment processing',
          'Real-time features',
          'Offline functionality',
          'Analytics integration',
          'Full admin dashboard',
          'API documentation',
          '3 months free support',
        ],
      },
      {
        id: 'app-enterprise',
        name: 'Enterprise',
        priceNGN: 0,
        priceUSD: 0,
        billingType: 'custom',
        delivery: 'Custom timeline',
        description: 'Full product build with dedicated team',
        features: [
          'Everything in Pro',
          'AI/ML integration',
          'IoT connectivity',
          'Blockchain features',
          'Dedicated dev team',
          'Ongoing maintenance',
          'SLA guarantee',
          'Priority support',
        ],
        isCustom: true,
        badge: 'Contact Us',
      },
    ],
  },

  // â”€â”€ SOCIAL MEDIA MANAGEMENT â”€â”€
  {
    id: 'social-media-management',
    slug: 'social-media-management',
    name: 'Social Media Management',
    tagline: 'Consistent, engaging social media presence that grows your brand',
    description: 'We manage your social media accounts with strategic content, eye-catching graphics, and community engagement. Focus on your business while we grow your audience.',
    category: 'marketing',
    icon: '📣',
    startingPriceNGN: 75000,
    startingPriceUSD: 53,
    billingType: 'monthly',
    payOnline: true,
    plans: [
      {
        id: 'smm-starter',
        name: 'Starter',
        priceNGN: 75000,
        priceUSD: 53,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Get started with consistent social media presence',
        features: [
          '1 platform (IG or FB)',
          '12 posts per month',
          'Professional graphics',
          'Caption copywriting',
          'Hashtag strategy',
          'Monthly performance report',
          'WhatsApp support',
        ],
      },
      {
        id: 'smm-growth',
        name: 'Growth',
        priceNGN: 150000,
        priceUSD: 107,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Grow your brand across multiple platforms',
        features: [
          '2 platforms (IG + FB)',
          '20 posts per month',
          'Premium graphics + video',
          'Story content (5/week)',
          'Community management',
          'Engagement responses',
          'Content calendar',
          'Weekly performance report',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'smm-scale',
        name: 'Scale',
        priceNGN: 250000,
        priceUSD: 178,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Full social media domination across all platforms',
        features: [
          '3 platforms (IG + FB + TikTok)',
          '30 posts per month',
          'Reels + TikTok videos (8/month)',
          'Story content daily',
          'Community management',
          'Influencer outreach',
          'Paid ads management',
          'Competitor monitoring',
          'Daily performance report',
        ],
      },
      {
        id: 'smm-enterprise',
        name: 'Enterprise',
        priceNGN: 500000,
        priceUSD: 357,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Complete social media department for large brands',
        features: [
          'All platforms',
          'Unlimited content creation',
          'Dedicated content team',
          'Brand strategy sessions',
          'Influencer partnerships',
          'PR & media outreach',
          'Monthly strategy meeting',
          'Full analytics dashboard',
          'Priority support',
        ],
      },
    ],
  },

  // â”€â”€ MUSIC PROMOTION â”€â”€
  {
    id: 'music-promotion',
    slug: 'music-promotion',
    name: 'Music Promotion',
    tagline: 'Get your music heard by millions across Africa and beyond',
    description: 'Strategic music promotion campaigns across TikTok, Instagram, YouTube, and streaming platforms. We help artists build real fanbase and streaming numbers.',
    category: 'music',
    icon: '🎵',
    startingPriceNGN: 30000,
    startingPriceUSD: 21,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'music-buzz',
        name: 'Buzz',
        priceNGN: 30000,
        priceUSD: 21,
        billingType: 'one-time',
        delivery: '7 days',
        description: 'Create initial buzz for your new release',
        features: [
          '1 song promotion',
          'TikTok + Instagram push',
          '50K+ reach target',
          'Story mentions',
          'Basic playlist pitching',
          '7-day campaign',
          'Campaign report',
        ],
      },
      {
        id: 'music-viral',
        name: 'Viral',
        priceNGN: 75000,
        priceUSD: 53,
        billingType: 'one-time',
        delivery: '14 days',
        description: 'Targeted campaign to go viral on social media',
        features: [
          '1 song promotion',
          'TikTok + IG + YouTube Shorts',
          '200K+ reach target',
          'Playlist pitching (5 playlists)',
          'Blog feature (2 blogs)',
          'Influencer story mentions',
          '14-day campaign',
          'Detailed analytics report',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'music-superstar',
        name: 'Superstar',
        priceNGN: 150000,
        priceUSD: 107,
        billingType: 'one-time',
        delivery: '30 days',
        description: 'Full campaign for serious artists and EP/Albums',
        features: [
          '1 song OR EP/Album',
          'All social media platforms',
          '500K+ reach target',
          'Playlist pitching (15 playlists)',
          'Press release distribution',
          'Blog features (5 blogs)',
          'Radio pitching',
          'Influencer collaborations',
          '30-day campaign',
          'Full analytics report',
        ],
      },
      {
        id: 'music-label',
        name: 'Label Deal',
        priceNGN: 0,
        priceUSD: 0,
        billingType: 'custom',
        delivery: 'Custom',
        description: 'Full artist campaign management like a record label',
        features: [
          'Full album campaign',
          'Distribution included',
          'Brand partnerships',
          'Radio pitching',
          'TV/media appearances',
          'Merchandise strategy',
          'Dedicated campaign manager',
          'Monthly strategy sessions',
        ],
        isCustom: true,
        badge: 'Contact Us',
      },
    ],
  },

  // â”€â”€ MUSIC DISTRIBUTION â”€â”€
  {
    id: 'music-distribution',
    slug: 'music-distribution',
    name: 'Music Distribution',
    tagline: 'Get your music on 150+ platforms including Spotify and Apple Music',
    description: 'Professional music distribution to all major streaming platforms worldwide. Keep most of your royalties and get paid monthly. ISRC and UPC codes included.',
    category: 'music',
    icon: '🎧',
    startingPriceNGN: 15000,
    startingPriceUSD: 10,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'dist-single',
        name: 'Single',
        priceNGN: 15000,
        priceUSD: 10,
        billingType: 'one-time',
        delivery: '2-5 business days',
        description: 'Distribute one single to all major platforms',
        features: [
          '1 single (up to 2 tracks)',
          '150+ streaming platforms',
          'Spotify, Apple Music, Boomplay',
          'ISRC code included',
          'Keep 80% royalties',
          'Monthly royalty payments',
          'Streaming stats dashboard',
        ],
      },
      {
        id: 'dist-album',
        name: 'Album / EP',
        priceNGN: 35000,
        priceUSD: 25,
        billingType: 'one-time',
        delivery: '2-5 business days',
        description: 'Distribute your EP or full album worldwide',
        features: [
          'Up to 15 tracks',
          '150+ streaming platforms',
          'All major platforms worldwide',
          'UPC + ISRC codes included',
          'Keep 85% royalties',
          'Monthly royalty payments',
          'Streaming analytics',
          'Playlist pitching support',
        ],
        highlighted: true,
        badge: 'Best Value',
      },
      {
        id: 'dist-artist',
        name: 'Artist Plan',
        priceNGN: 75000,
        priceUSD: 53,
        billingType: 'yearly',
        delivery: '2-5 business days',
        description: 'Unlimited releases for one full year',
        features: [
          'Unlimited releases per year',
          '150+ streaming platforms',
          'All platforms worldwide',
          'UPC + ISRC codes included',
          'Keep 90% royalties',
          'Monthly royalty payments',
          'Priority distribution',
          'Dedicated artist support',
          'Free music promotion boost',
        ],
      },
    ],
  },

  // â”€â”€ ACCOUNT RECOVERY â”€â”€
  {
    id: 'account-recovery',
    slug: 'account-recovery',
    name: 'Account Recovery',
    tagline: 'Professional recovery for hacked or disabled social media accounts',
    description: 'Specialist recovery service for suspended, hacked, or disabled social media accounts. We use official appeal processes with high success rates. Full refund if unsuccessful.',
    category: 'support',
    icon: '🔐',
    startingPriceNGN: 42000,
    startingPriceUSD: 30,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'recovery-facebook',
        name: 'Facebook Recovery',
        priceNGN: 42000,
        priceUSD: 30,
        billingType: 'one-time',
        delivery: '14-30 business days',
        description: 'Recover hacked or disabled Facebook account or page',
        features: [
          'Personal or business account',
          'Facebook page recovery',
          'Official appeal process',
          'ID verification support',
          '14-30 business days',
          '70% success rate',
          'Progress updates via WhatsApp',
          'Full refund if unsuccessful',
        ],
      },
      {
        id: 'recovery-instagram',
        name: 'Instagram Recovery',
        priceNGN: 75000,
        priceUSD: 53,
        billingType: 'one-time',
        delivery: '14-30 business days',
        description: 'Recover hacked or disabled Instagram account',
        features: [
          'Personal or creator account',
          'Business account recovery',
          'Official Meta appeal process',
          'ID verification support',
          '14-30 business days',
          '70% success rate',
          'Progress updates via WhatsApp',
          'Full refund if unsuccessful',
        ],
      },
      {
        id: 'recovery-tiktok',
        name: 'TikTok Recovery',
        priceNGN: 75000,
        priceUSD: 53,
        billingType: 'one-time',
        delivery: '14-30 business days',
        description: 'Recover banned or disabled TikTok account',
        features: [
          'Personal or creator account',
          'TikTok official appeal',
          'ID verification support',
          '14-30 business days',
          '70% success rate',
          'Progress updates via WhatsApp',
          'Full refund if unsuccessful',
        ],
      },
      {
        id: 'recovery-twitter',
        name: 'Twitter/X Recovery',
        priceNGN: 60000,
        priceUSD: 42,
        billingType: 'one-time',
        delivery: '14-21 business days',
        description: 'Recover suspended Twitter/X account',
        features: [
          'Personal or business account',
          'X official appeal process',
          'ID verification support',
          '14-21 business days',
          '65% success rate',
          'Progress updates via WhatsApp',
          'Full refund if unsuccessful',
        ],
      },
      {
        id: 'recovery-gmail',
        name: 'Gmail/Google Recovery',
        priceNGN: 50000,
        priceUSD: 35,
        billingType: 'one-time',
        delivery: '7-21 business days',
        description: 'Recover locked Google or Gmail account',
        features: [
          'Gmail or Google account',
          'Google official recovery',
          'ID verification support',
          '7-21 business days',
          '75% success rate',
          'Progress updates via WhatsApp',
          'Full refund if unsuccessful',
        ],
      },
    ],
  },

  // â”€â”€ UI/UX DESIGN â”€â”€
  {
    id: 'ui-ux-design',
    slug: 'ui-ux-design',
    name: 'UI/UX Design',
    tagline: 'Pixel-perfect designs that users love and convert',
    description: 'We design beautiful, intuitive interfaces for web apps, mobile apps, and dashboards. From wireframes to interactive prototypes â€” with full Figma handoff.',
    category: 'design',
    icon: '🎨',
    startingPriceNGN: 150000,
    startingPriceUSD: 107,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'ux-basic',
        name: 'Basic',
        priceNGN: 150000,
        priceUSD: 107,
        billingType: 'one-time',
        delivery: '1-2 weeks',
        description: 'Clean design for simple apps or websites',
        features: [
          'Up to 5 screens/pages',
          'Mobile or web design',
          'Wireframes + mockups',
          'Figma file delivery',
          'Basic design system',
          '2 revision rounds',
          'Developer handoff notes',
        ],
      },
      {
        id: 'ux-standard',
        name: 'Standard',
        priceNGN: 300000,
        priceUSD: 214,
        billingType: 'one-time',
        delivery: '2-4 weeks',
        description: 'Full design for medium-complexity products',
        features: [
          'Up to 15 screens/pages',
          'Mobile + web responsive',
          'Full design system',
          'Interactive prototype',
          'Component library',
          'Developer handoff (Figma)',
          '4 revision rounds',
          'Style guide document',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'ux-premium',
        name: 'Premium',
        priceNGN: 600000,
        priceUSD: 428,
        billingType: 'one-time',
        delivery: '4-6 weeks',
        description: 'Complete product design with research and testing',
        features: [
          'Unlimited screens',
          'User research included',
          'Full design system',
          'Interactive prototype',
          'Usability testing',
          'Accessibility audit',
          'Brand integration',
          'Unlimited revisions',
          'Post-delivery support',
        ],
      },
      {
        id: 'ux-enterprise',
        name: 'Enterprise',
        priceNGN: 0,
        priceUSD: 0,
        billingType: 'custom',
        delivery: 'Custom timeline',
        description: 'Ongoing design support for large products',
        features: [
          'Everything in Premium',
          'Multiple products/apps',
          'Design sprint workshops',
          'Dedicated designer',
          'Ongoing design retainer',
          'Monthly design reviews',
        ],
        isCustom: true,
        badge: 'Contact Us',
      },
    ],
  },

  // â”€â”€ LOGO DESIGN â”€â”€
  {
    id: 'logo-design',
    slug: 'logo-design',
    name: 'Logo Design',
    tagline: 'Memorable logos that represent your brand perfectly',
    description: 'Professional logo design that captures your brand identity. From simple clean logos to full brand identity packages â€” all delivered in print and digital ready formats.',
    category: 'design',
    icon: '✏️',
    startingPriceNGN: 25000,
    startingPriceUSD: 17,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'logo-basic',
        name: 'Basic',
        priceNGN: 25000,
        priceUSD: 17,
        billingType: 'one-time',
        delivery: '3-5 business days',
        description: 'Clean professional logo for startups and small businesses',
        features: [
          '2 unique logo concepts',
          'PNG + JPG file formats',
          'White + dark background versions',
          'Transparent background PNG',
          'Social media ready sizes',
          '2 revision rounds',
          '3-5 business days',
        ],
      },
      {
        id: 'logo-standard',
        name: 'Standard',
        priceNGN: 60000,
        priceUSD: 42,
        billingType: 'one-time',
        delivery: '5-7 business days',
        description: 'Professional logo with full file package',
        features: [
          '4 unique logo concepts',
          'All file formats (AI, PDF, PNG, SVG)',
          'White + dark + color versions',
          'Favicon version',
          'Simple brand color guide',
          'Font recommendations',
          'Unlimited revisions',
          '5-7 business days',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'logo-premium',
        name: 'Premium',
        priceNGN: 120000,
        priceUSD: 85,
        billingType: 'one-time',
        delivery: '7-10 business days',
        description: 'Complete logo with brand style guide',
        features: [
          '6 unique logo concepts',
          'All file formats',
          'Complete brand style guide',
          'Color palette (primary + secondary)',
          'Typography guide',
          'Business card mockup',
          'Social media profile kit',
          'Letterhead mockup',
          'Unlimited revisions',
        ],
      },
      {
        id: 'logo-brand',
        name: 'Brand Identity',
        priceNGN: 250000,
        priceUSD: 178,
        billingType: 'one-time',
        delivery: '2-3 weeks',
        description: 'Full brand identity package for serious businesses',
        features: [
          'Everything in Premium',
          'Full brand identity system',
          'Business card design (print-ready)',
          'Letterhead + invoice template',
          'Email signature design',
          'Social media templates (10)',
          'Brand guidelines document (PDF)',
          'Brand launch strategy',
          'Unlimited revisions',
        ],
      },
    ],
  },

  // â”€â”€ SEO & CONTENT â”€â”€
  {
    id: 'seo-content',
    slug: 'seo-content',
    name: 'SEO & Content Marketing',
    tagline: 'Rank higher on Google and drive organic traffic that converts',
    description: 'Strategic SEO and content marketing to grow your organic traffic. We handle keyword research, on-page optimization, backlink building, and content creation.',
    category: 'marketing',
    icon: '🔍',
    startingPriceNGN: 40000,
    startingPriceUSD: 28,
    billingType: 'monthly',
    payOnline: true,
    plans: [
      {
        id: 'seo-basic',
        name: 'Basic',
        priceNGN: 40000,
        priceUSD: 28,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Start your SEO journey with essential optimizations',
        features: [
          '5 blog posts per month',
          'Keyword research (20 keywords)',
          'On-page SEO optimization',
          'Google Search Console setup',
          'Google Analytics setup',
          'Meta tags optimization',
          'Monthly ranking report',
        ],
      },
      {
        id: 'seo-standard',
        name: 'Standard',
        priceNGN: 80000,
        priceUSD: 57,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Comprehensive SEO for growing businesses',
        features: [
          '10 blog posts per month',
          'Keyword research (50 keywords)',
          'Full technical SEO audit',
          'Backlink building (10/month)',
          'Local SEO optimization',
          'Competitor analysis',
          'Schema markup',
          'Weekly ranking report',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'seo-premium',
        name: 'Premium',
        priceNGN: 150000,
        priceUSD: 107,
        billingType: 'monthly',
        delivery: 'Monthly',
        description: 'Full SEO management for market dominance',
        features: [
          '20 blog posts per month',
          'Full keyword strategy',
          'Technical SEO management',
          'Backlink building (30/month)',
          'Press release distribution',
          'Video SEO optimization',
          'Content strategy planning',
          'Dedicated SEO manager',
          'Daily rank monitoring',
          'Monthly strategy meeting',
        ],
      },
    ],
  },

  // â”€â”€ VIDEO CONTENT â”€â”€
  {
    id: 'video-content',
    slug: 'video-content-creation',
    name: 'Video Content Creation',
    tagline: 'Professional videos that capture attention and drive engagement',
    description: 'High-quality video production for social media, brand campaigns, product demos, and more. From concept to final delivery â€” optimized for all platforms.',
    category: 'content',
    icon: '🎬',
    startingPriceNGN: 50000,
    startingPriceUSD: 35,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'video-basic',
        name: 'Basic',
        priceNGN: 50000,
        priceUSD: 35,
        billingType: 'one-time',
        delivery: '3-5 business days',
        description: 'Short social media video for one platform',
        features: [
          '1 short video (up to 60 sec)',
          'Social media optimized',
          'Basic editing + transitions',
          'Background music',
          'Captions/subtitles',
          '1 platform format',
          '1 revision round',
        ],
      },
      {
        id: 'video-standard',
        name: 'Standard',
        priceNGN: 120000,
        priceUSD: 85,
        billingType: 'one-time',
        delivery: '5-7 business days',
        description: 'Multiple short videos or one longer video',
        features: [
          '3 short videos OR 1 long video (5-10 min)',
          'Professional editing',
          'Motion graphics + animations',
          'Brand colors/logo integration',
          'Multiple format delivery',
          'Background music',
          'Captions/subtitles',
          '2 revision rounds',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'video-premium',
        name: 'Premium',
        priceNGN: 250000,
        priceUSD: 178,
        billingType: 'one-time',
        delivery: '7-14 business days',
        description: 'Premium video package with scriptwriting',
        features: [
          '5 short videos OR 2 long videos',
          'Script writing included',
          'Storyboard planning',
          'Professional voiceover',
          'Advanced motion graphics',
          'Brand animations',
          'All platform formats',
          'Unlimited revisions',
        ],
      },
      {
        id: 'video-brand',
        name: 'Brand Video',
        priceNGN: 500000,
        priceUSD: 357,
        billingType: 'one-time',
        delivery: '2-4 weeks',
        description: 'Full brand or promotional video production',
        features: [
          'Full brand/promo video (2-5 min)',
          'Script + storyboard',
          'Professional voiceover',
          '3D animations if needed',
          'Color grading',
          'Sound design',
          'All platform formats',
          'Unlimited revisions',
          'Usage rights included',
        ],
      },
    ],
  },

  // â”€â”€ BRANDING â”€â”€
  {
    id: 'branding',
    slug: 'branding-creative-design',
    name: 'Branding & Creative Design',
    tagline: 'Build a brand identity that commands attention and trust',
    description: 'Complete brand identity creation from strategy to execution. We craft visual identities that tell your story, differentiate you from competitors, and connect with your target audience.',
    category: 'design',
    icon: '💎',
    startingPriceNGN: 150000,
    startingPriceUSD: 107,
    billingType: 'one-time',
    payOnline: true,
    plans: [
      {
        id: 'brand-starter',
        name: 'Starter Brand',
        priceNGN: 150000,
        priceUSD: 107,
        billingType: 'one-time',
        delivery: '1-2 weeks',
        description: 'Essential brand identity for new businesses',
        features: [
          'Logo design (3 concepts)',
          'Brand color palette',
          'Typography selection',
          'Basic brand guidelines (PDF)',
          'Business card design',
          'Email signature design',
          'PNG + SVG files',
          '2 revision rounds',
        ],
      },
      {
        id: 'brand-full',
        name: 'Full Brand',
        priceNGN: 350000,
        priceUSD: 250,
        billingType: 'one-time',
        delivery: '2-4 weeks',
        description: 'Complete brand identity for established businesses',
        features: [
          'Everything in Starter',
          'Full brand strategy document',
          'Social media templates (20)',
          'Letterhead + invoice template',
          'Proposal/presentation template',
          'Brand pattern/texture design',
          'Comprehensive brand guide',
          'Unlimited revisions',
        ],
        highlighted: true,
        badge: 'Most Popular',
      },
      {
        id: 'brand-premium',
        name: 'Premium Brand',
        priceNGN: 600000,
        priceUSD: 428,
        billingType: 'one-time',
        delivery: '4-6 weeks',
        description: 'Premium brand with website and video',
        features: [
          'Everything in Full Brand',
          'Landing page design',
          'Brand video (30 sec)',
          'Packaging design mockup',
          'Marketing materials design',
          'Brand launch strategy',
          'Dedicated brand manager',
          'Unlimited revisions',
        ],
      },
      {
        id: 'brand-enterprise',
        name: 'Enterprise Brand',
        priceNGN: 0,
        priceUSD: 0,
        billingType: 'custom',
        delivery: 'Custom timeline',
        description: 'Complete brand overhaul for large organizations',
        features: [
          'Everything in Premium',
          'Full market research',
          'Brand positioning strategy',
          'Complete rebrand management',
          'Staff brand training',
          'Ongoing brand management',
          'Quarterly brand audits',
        ],
        isCustom: true,
        badge: 'Contact Us',
      },
    ],
  },

  // â”€â”€ SAAS DEVELOPMENT â”€â”€
  {
    id: 'saas-development',
    slug: 'saas-development',
    name: 'SaaS Development',
    tagline: 'Build your software product with a team that delivers',
    description: 'End-to-end SaaS product development from idea to launch. We build scalable, secure, and maintainable software products. Subscription billing, user management, and admin dashboards included.',
    category: 'development',
    icon: '⚡',
    startingPriceNGN: 1500000,
    startingPriceUSD: 1071,
    billingType: 'one-time',
    payOnline: false,
    plans: [
      {
        id: 'saas-mvp',
        name: 'MVP',
        priceNGN: 1500000,
        priceUSD: 1071,
        billingType: 'one-time',
        delivery: '8-12 weeks',
        description: 'Launch your MVP and validate your idea fast',
        features: [
          'Core SaaS features',
          'User authentication system',
          'Subscription billing (Paystack)',
          'Basic admin dashboard',
          'User dashboard',
          'Email notifications',
          'Mobile responsive',
          '2 months free support',
        ],
      },
      {
        id: 'saas-growth',
        name: 'Growth',
        priceNGN: 3000000,
        priceUSD: 2142,
        billingType: 'one-time',
        delivery: '12-20 weeks',
        description: 'Full SaaS platform ready to scale',
        features: [
          'Everything in MVP',
          'Multi-tenant architecture',
          'Advanced billing (tiers + usage)',
          'Full admin dashboard',
          'Analytics & reporting',
          'API development',
          'API documentation',
          'Third-party integrations',
          '3 months free support',
        ],
        highlighted: true,
        badge: 'Recommended',
      },
      {
        id: 'saas-enterprise',
        name: 'Enterprise',
        priceNGN: 0,
        priceUSD: 0,
        billingType: 'custom',
        delivery: 'Custom timeline',
        description: 'Custom SaaS for complex business needs',
        features: [
          'Everything in Growth',
          'AI/ML integration',
          'Custom integrations',
          'Dedicated dev team',
          'Ongoing maintenance',
          'SLA guarantee',
          'Priority support',
          'Staff training',
        ],
        isCustom: true,
        badge: 'Contact Us',
      },
    ],
  },
]

// â”€â”€ HELPER FUNCTIONS â”€â”€

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find(s => s.slug === slug || s.id === slug)
}

export function getServicesByCategory(category: ServiceCategory): Service[] {
  return SERVICES.filter(s => s.category === category)
}

export function formatPrice(amount: number, currency: 'NGN' | 'USD' = 'NGN'): string {
  if (amount === 0) return 'Custom'
  if (currency === 'NGN') {
    return `â‚¦${amount.toLocaleString()}`
  }
  return `$${amount.toLocaleString()}`
}

export function getPlanById(planId: string): ServicePlan | undefined {
  for (const service of SERVICES) {
    const plan = service.plans.find(p => p.id === planId)
    if (plan) return plan
  }
  return undefined
}

export function getServiceByPlanId(planId: string): Service | undefined {
  return SERVICES.find(s => s.plans.some(p => p.id === planId))
}

export const EXCHANGE_RATE = 1400
// â‚¦1,400 = $1 USD

